services:
  client:
    image: localhost:5000/client:latest
    environment:
      - INTERACTIVE=false
      - SERVER_URL=ws://192.168.69.10:8080
    network_mode: host
    deploy:
      mode: replicated
      replicas: 3
    restart: always

networks:
  default:
    driver: bridge
